<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QUSVQOE" failures="4" tests="15" name="Test" time="29.954" errors="0" timestamp="2024-09-27T12:55:23 IST">
  <testcase classname="api.test.userTest" name="Testpostuser" time="5.415"/>
  <testcase classname="api.test.userTest" name="testgetuserbyname" time="1.271"/>
  <testcase classname="api.test.userTest" name="Testupdateuserbyname" time="2.546"/>
  <testcase classname="api.test.userTest" name="TestdeleteUser" time="1.303"/>
  <testcase classname="api.test.petorderTest" name="testpostuser1" time="1.167"/>
  <testcase classname="api.test.userTestnew" name="Testpostuser" time="1.981">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.userTestnew.Testpostuser(userTestnew.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- Testpostuser -->
  <testcase classname="api.test.userTestnew" name="testgetuserbyname" time="1.217">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.userTestnew.testgetuserbyname(userTestnew.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testgetuserbyname -->
  <testcase classname="api.test.userTestnew" name="Testupdateuserbyname" time="1.156">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.userTestnew.Testupdateuserbyname(userTestnew.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- Testupdateuserbyname -->
  <testcase classname="api.test.userTestnew" name="TestdeleteUser" time="1.163">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.userTestnew.TestdeleteUser(userTestnew.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- TestdeleteUser -->
  <testcase classname="api.test.DDTEST" name="testpostuser" time="1.159"/>
  <testcase classname="api.test.DDTEST" name="testpostuser" time="1.605"/>
  <testcase classname="api.test.DDTEST" name="testpostuser" time="2.49"/>
  <testcase classname="api.test.DDTEST" name="Testdelete" time="1.135"/>
  <testcase classname="api.test.DDTEST" name="Testdelete" time="1.145"/>
  <testcase classname="api.test.DDTEST" name="Testdelete" time="1.167"/>
</testsuite> <!-- Test -->
